Re structure backend code
rubra-ai/rubra pull request #89
Opened 2024-02-20 23:24 UTC by tybalex

move key logics, includeing data models, tools, tasks executor tasks... etc to dir `/core`,
and each service has its own APIs only.

This also removes a lot of duplicated code in different services folders.

2024-02-20 23:34 UTC, sanjay920 commented on Makefile
> +			docker build -t $$FULL_TAG -f $$dir/Dockerfile .; \
why is this change necessary?

2024-02-20 23:49 UTC, sanjay920 approved these changes

2024-02-21 01:20 UTC, cloudnautique requested changes
The build context needs to be added to the build and push image target

`docker buildx build --build-context core=./core`

2024-02-21 17:44 UTC, tybalex commented
> The build context needs to be added to the build and push image target
> 
> `docker buildx build --build-context core=./core`

updated.

2024-02-21 22:53 UTC, merged